services:
  pg:
    ports:
      - "127.0.0.1:5432:5432"
  
  authorization-app:
    build: 
      context: ./Authorization
      dockerfile: Dockerfile
    volumes:
      - ./Authorization/app:/app
    environment:
      - DATABASE__CONNECTIONSTRING=Host=pg;Port=5432;Database=authdb;Username=postgres;Password=postgres
      - JWT_KEY=18Z0Vmuq5j99VY0X1xkIVlZ499t3SqHha7siBG29tnb4WAuR
    entrypoint: dotnet watch run --urls http://0.0.0.0:8080

  content-app:
    volumes:
      - ./Content/app:/app/app
    command: "--log-level debug --reload --reload-dir /app/"

  recommendations-app:
    volumes:
      - ./Recommendations/app:/app/app

  search-app:
    volumes:
      - ./Search/app:/app/app
    environment:
      - WATCHFILES_FORCE_POLLING=true
    entrypoint: "uvicorn app.main:app --host 0.0.0.0 --port 8080 --log-level debug --reload --reload-dir /app/"

  profile-app:
    volumes:
      - ./Profile/app:/app/app
      - ./Profile/migrations:/app/migrations
    command: "--log-level debug --reload --reload-dir /app/"

