services:
  search-app:
    volumes:
      - ./app:/app/app
    env_file:
      - path: .env
        required: false

  nginx:
    image: nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro