# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_api
    ports:
      - 5433:5432

  authorization-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - DATABASE__CONNECTIONSTRING=Host=db;Port=5432;Database=auth_api;Username=postgres;Password=postgres
      - JWT_KEY=18Z0Vmuq5j99VY0X1xkIVlZ499t3SqHha7siBG29tnb4WAuR
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8080/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    entrypoint: dotnet watch run --urls http://0.0.0.0:8080

  nginx:
    image: nginx
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      authorization-app:
        condition: service_healthy

        
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

volumes:
  dbdata:
