name: Detect and Trigger Service Builds

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      authorization: ${{ steps.filter.outputs.Authorization }}
      content: ${{ steps.filter.outputs.Content }}
      recommendations: ${{ steps.filter.outputs.Recommendations }}
      search: ${{ steps.filter.outputs.Search }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            Authorization:
              - 'Authorization/**'
            Content:
              - 'Content/**'
            Recommendations:
              - 'Recommendations/**'
            Search:
              - 'Search/**'

  trigger-authorization:
    needs: detect-changes
    if: needs.detect-changes.outputs.authorization == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/service-authorization.yml

  trigger-content:
    needs: detect-changes
    if: needs.detect-changes.outputs.content == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/service-content.yml

  trigger-recommendations:
    needs: detect-changes
    if: needs.detect-changes.outputs.recommendations == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/service-recommendations.yml

  trigger-search:
    needs: detect-changes
    if: needs.detect-changes.outputs.search == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/service-search.yml