name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  trigger-main:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: main-ci.yml
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
