name: Manual Trigger for Build & Push

on:
  workflow_dispatch:

jobs:
  trigger-authorization:
    uses: ./.github/workflows/service-authorization.yml

  trigger-content:
    uses: ./.github/workflows/service-content.yml

  trigger-recommendations:
    uses: ./.github/workflows/service-recommendations.yml

  trigger-search:
    uses: ./.github/workflows/service-search.yml