name: Build and Push Authorization Service

on:
  workflow_call:

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: authorization

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.SERVICE_NAME }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.SERVICE_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}